version: "3.8"
services:
    web: 
        image: nginx:alpine
        restart: always
        user: "${MY_UID}:${MY_GID}"
        volumes:
            - ./default-html:/var/www/html
            - ./conf.d:/etc/nginx/conf.d:ro
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/certbot
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email pecato2003@arpizol.com --agree-tos --no-eff-email -d vds-868ba4.1gb.ru -d www.vds-868ba4.1gb.ru
        user: "${MY_UID}:${MY_GID}"
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/certbot